### ISSUE TITLE
Create a branch for team 1

### ISSUE THREAD

**Issue by EmbeddedSWUDG** [EmbeddedSWUDG/UDG_2017_B#1]
Create a new branch for team 1 working projects. Every single member of the team must do a modification into the branch.

**Comment by omaresl** [comment]
@riquiochoa and @Arodripre has been committed some changes into the team branch.

@FerOchoaSada must create the final branch for the team and commit a change into the function code

**Comment by omaresl** [comment]
@FerOchoaSada Solo faltas tu de subir cambios. La tardanza esta justificada en parte por que has tenido problemas con tu instalacion de MCUXpresso. Sin embargo esto no puede quedar asi ya que no podrias trabajar en el futuro. Voy a cerrar el Issue generado en git pero para tu practica debemos arreglar ese problema.
