### ISSUE TITLE
Create a branch for Jorlando

### ISSUE THREAD

**Issue by EmbeddedSWUDG** [EmbeddedSWUDG/UDG_2017_B#2]
@JorlandoMonts Must create a new branch from master development path

**Comment by EmbeddedSWUDG** [comment]
@JorlandoMonts Has creado mas de un branch. La idea es

**Comment by omaresl** [comment]
@JorlandoMonts Creaste mas de un branch. La idea es crear un branch e ir añadiendo modificaciones sobre esa linea. Tu creaste un branch por modificacion y eso puede llevar a un seguimiento mas complicado del proyecto.
