### ISSUE TITLE
Create Branch for Team 2

### ISSUE THREAD

**Issue by EmbeddedSWUDG** [EmbeddedSWUDG/UDG_2017_B#4]
Create a new branch for Team 2 Develop

Every member has to made at least one change using their Git user.

**Comment by omaresl** [comment]
Equipo 2

Hasta ahora solo Ricardo Reyes ha añadido cambios en el branch creado por Alejandro Garcia. Necesito que Alejandro y Aldo agreguen algun cambio dentro del branch para que la practica este completa.

**Comment by aldov500** [comment]
Profesor, ya le enviamos los cambios que hacían falta. Saludos

2017-10-18 8:56 GMT-05:00 Omar Sevilla <notifications@github.com>:

**Comment by omaresl** [comment]
Excelente Equipo 2.

Actualizare las calificaciones.

100 a todos en la practica

**Comment by aldov500** [comment]
Gracias profesor por el apoyo, saludos

2017-10-19 9:05 GMT-05:00 Omar Sevilla <notifications@github.com>:
